# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "NotTim/local/root";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "NotTim/local/var";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "NotTim/local/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "NotTim/safe/home";
      fsType = "zfs";
    };

  fileSystems."/etc/nixos" =
    { device = "NotTim/safe/nixconfig";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/98CB-CD0A";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/83a94b1c-a959-4dcc-994b-5640edc54228"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
